In [1]:
import numpy as np

In [15]:
x = np.arange(1, 11)
y = np.arange(11, 21)

In [16]:
[i + 2 for i in range(1, 11)]

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [20]:
# Same as in thie way!
np.add(x, 2)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
np.add(x, y)

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [22]:
x - y

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [25]:
np.round(x / y, 2)

array([0.09, 0.17, 0.23, 0.29, 0.33, 0.38, 0.41, 0.44, 0.47, 0.5 ])

In [26]:
np.abs(x - y)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [30]:
np.exp2(x)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [31]:
np.power(y, x)

array([         11,         144,        2197,       38416,      759375,
          16777216,   410338673, -1864941312,   565150579,   797966336],
      dtype=int32)

In [32]:
np.power(2, x)

array([   2,    4,    8,   16,   32,   64,  128,  256,  512, 1024],
      dtype=int32)

In [34]:
np.round(np.log(x), 2)

array([0.  , 0.69, 1.1 , 1.39, 1.61, 1.79, 1.95, 2.08, 2.2 , 2.3 ])

In [39]:
# SUM
    # np.sum(x) OR x.sum()
x = np.array([70, 80, 100, 90, 80], dtype='int64')

In [40]:
print(x.sum())
print(np.sum(x))

420
420


In [41]:
np.prod(x)

4032000000

In [42]:
print(x.mean())
print(np.mean(x))

84.0
84.0


In [43]:
print(x.std())
print(np.std(x))

10.198039027185569
10.198039027185569


In [44]:
np.max(x)

100

In [45]:
np.min(x)

70

In [46]:
np.argmax(x) #Max Value iLoc

2

In [48]:
np.argmin(x) #Min Value iLoc

0

In [49]:
y = np.array([90,90,90,80,80])
y[np.argmax(x)] # x 과목의 1등 학생의 y 과목 점수

90

In [50]:
np.median(x)

80.0

In [51]:
np.percentile(x, 25)

80.0

In [52]:
np.percentile(x, 75)

90.0

In [53]:
np.nansum(x) # NaN value는 무시한 채 sum 구하기

420