In [1]:
import numpy as np

In [6]:
x = np.random.randint(1, 10, (3,3))
x

array([[5, 6, 1],
       [3, 2, 3],
       [2, 1, 5]])

In [8]:
y = np.random.randint(1, 4, 3)
y

array([1, 1, 3])

In [9]:
x + y

array([[6, 7, 4],
       [4, 3, 6],
       [3, 2, 8]])

In [10]:
# y의 Row 수가 3개로 확장되고, 1st Row의 값들이 copy 됨

In [11]:
z = np.random.randint(1, 4, (2,2))
z

array([[3, 2],
       [2, 3]])

In [13]:
# broadcasting Error
x + z

ValueError: operands could not be broadcast together with shapes (3,3) (2,2) 

In [15]:
x = np.random.randint(10, size=(3,4))
x

array([[3, 2, 7, 8],
       [7, 5, 3, 8],
       [5, 0, 8, 1]])

In [16]:
x < 6

array([[ True,  True, False, False],
       [False,  True,  True, False],
       [ True,  True, False,  True]])

In [17]:
# elements which are less than 6
x[x < 6]

array([3, 2, 5, 3, 5, 0, 1])

In [19]:
# number of elements which are less then 6
np.sum(x < 6)

7

In [20]:
x

array([[3, 2, 7, 8],
       [7, 5, 3, 8],
       [5, 0, 8, 1]])

In [22]:
np.sum(x, axis=0) # Row를 바꿔가면서 합계내기

array([15,  7, 18, 17])

In [23]:
np.sum(x, axis=1) # Column을 바꿔가면서 합계내기

array([20, 23, 14])

In [26]:
np.any(x > 7) #하나라도 True면 True

True

In [28]:
np.any(x > 7, axis=1) # Column을 바꿔가면서, 각 Row에 적용

array([ True,  True,  True])

In [30]:
np.any(x > 7, axis=0) # Row를 바꿔가면서, 각 Column에 적용

array([False, False,  True,  True])

In [33]:
np.all(x < 10) # 전부 다 True인 경우에만 True

True

In [36]:
np.mean(x > 7) # True인 항목들의 비율

0.25

In [37]:
np.mean(x > 7, axis=1) # Column을 바꿔가면서, 각 Row에 적용하여 비율 구하기

array([0.25, 0.25, 0.25])

In [40]:
np.mean(x > 7, axis=0).round(2) # Row를 바꿔가면서, 각 Column에 적용하여 비율 구하기

array([0.  , 0.  , 0.33, 0.67])