In [1]:
import numpy as np

In [4]:
[1,4,2,5]

[1, 4, 2, 5]

In [5]:
np.array([1,4,2,5])

array([1, 4, 2, 5])

In [6]:
# string > float > integer 순으로 dtype이 우선 배정된다.
np.array([1, 4, 2.5, 5])

array([1. , 4. , 2.5, 5. ])

In [7]:
# dtype='int'로 입력하면, float의 경우 반올림이 아닌, '내림' 형태로 integer로 변환한다.
np.array([1,4, 2.5, 5], dtype='int')

array([1, 4, 2, 5])

In [8]:
np.array([1, 'a', 2.5], dtype='<U11')

array(['1', 'a', '2.5'], dtype='<U11')

In [9]:
np.array([[1,2,3],
          [4,5,6], 
          [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.zeros((3,4), dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [15]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.ones(10, dtype='int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
np.ones((3,4), dtype='int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [20]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [23]:
np.arange(1, 11, 1).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [26]:
np.linspace(0, 1, 5, dtype='float')

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [31]:
np.random.random((3,3)).round(2)

array([[0.41, 0.7 , 0.25],
       [0.33, 0.33, 0.62],
       [0.86, 0.36, 0.4 ]])

In [33]:
# Avg. Payment = KRW 10,000, SD = KRW 2,000
np.random.normal(10000, 2000, (3,3)).round(1)

array([[10838. , 10366.6, 10673.1],
       [11630.1, 13134. ,  6627. ],
       [ 8634.5, 14320.5, 14353. ]])

In [34]:
# Standard Normal Distribution
np.random.normal(0, 1, (3,3)).round(1)

array([[-0.1, -0.3, -0.8],
       [ 1.7, -0.2, -2.9],
       [-0.3,  1. ,  0.8]])

In [35]:
np.random.randint(1, 11, (3,3))

array([[7, 6, 5],
       [1, 7, 7],
       [9, 4, 1]])